name: Metrics
on:
  # Aggiorna ogni 24 ore
  schedule: [{cron: "0 0 * * *"}]
  # Permette di eseguirlo manualmente
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Opzioni base
          user: LucaFavole  
          template: classic
          base: header, activity, community, repositories, metadata
          config_timezone: Europe/Rome
          
          # Plugins (per avere i dettagli che vedi nell'immagine)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_stars: yes
          plugin_followup: yes
